/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.luiz.view;

import com.luiz.DAO.JogadaDAO;
import com.luiz.model.Jogada;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luiz
 */
public class HistoricoPartidas extends javax.swing.JFrame {
 
            int contagemJog1 = 0;
            int contagemJog2 = 0;
    /**
     * Creates new form HistoricoPartidas
     */
    public HistoricoPartidas() {
        initComponents();
        readJTable();
    }

       public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) tableHistorico.getModel();
        modelo.setNumRows(0);
            JogadaDAO Gdao = new JogadaDAO();
            String jogador = null;
           
        for (Jogada p : Gdao.read()) {
                    if(p.getVencedorJogada() == 1){
                     jogador = "Jogador 1";
                     contagemJog1++;
                    }else if(p.getVencedorJogada() == 2){
                     jogador = "Jogador 2";
                     contagemJog2++;
                    }else if(p.getVencedorJogada() == 0){
                     jogador = "Empate";
                    }
                    
            modelo.addRow(new Object[]{jogador});
            lblContaVit1.setText(""+contagemJog1);
            lblContVit2.setText(""+contagemJog2);


        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableHistorico = new javax.swing.JTable();
        lblVitJogador1 = new javax.swing.JLabel();
        lblVitJog2 = new javax.swing.JLabel();
        lblContaVit1 = new javax.swing.JLabel();
        lblContVit2 = new javax.swing.JLabel();
        btnJogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Historico de partidas");

        tableHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Vencedor da partida"
            }
        ));
        jScrollPane1.setViewportView(tableHistorico);

        lblVitJogador1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblVitJogador1.setText("Vitórias para o jogador 1: ");

        lblVitJog2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblVitJog2.setText("Vitórias para o jogador 2: ");

        lblContaVit1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContaVit1.setForeground(new java.awt.Color(255, 51, 51));
        lblContaVit1.setText("jLabel1");

        lblContVit2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblContVit2.setForeground(new java.awt.Color(255, 0, 0));
        lblContVit2.setText("jLabel1");

        btnJogar.setText("JOGAR");
        btnJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVitJogador1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContaVit1)
                .addGap(79, 79, 79)
                .addComponent(btnJogar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVitJog2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContVit2)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVitJogador1)
                    .addComponent(lblVitJog2)
                    .addComponent(lblContaVit1)
                    .addComponent(lblContVit2)
                    .addComponent(btnJogar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        this.dispose();
        JogadaJog1 jogo = new JogadaJog1();
        jogo.setVisible(true);
    }//GEN-LAST:event_btnJogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoPartidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoPartidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoPartidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoPartidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoPartidas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJogar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblContVit2;
    private javax.swing.JLabel lblContaVit1;
    private javax.swing.JLabel lblVitJog2;
    private javax.swing.JLabel lblVitJogador1;
    private javax.swing.JTable tableHistorico;
    // End of variables declaration//GEN-END:variables
}
