/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.luiz.view;

import com.luiz.DAO.JogadaDAO;
import com.luiz.model.Jogada;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author luiz
 */
public class JogadaJog2 extends javax.swing.JFrame {
    static int jogada2;
    static int jogadaResultado;

    /**
     * Creates new form JogadaJog1
     */
    public JogadaJog2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pedraBtn = new javax.swing.JButton();
        papelBtn = new javax.swing.JButton();
        tesouraBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 48)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("Jogador 2");

        pedraBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/luiz/view/pedra.png"))); // NOI18N
        pedraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedraBtnActionPerformed(evt);
            }
        });

        papelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/luiz/view/papel.png"))); // NOI18N
        papelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                papelBtnActionPerformed(evt);
            }
        });

        tesouraBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/luiz/view/tesoura.png"))); // NOI18N
        tesouraBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tesouraBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(pedraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(papelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(tesouraBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jLabel1)))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tesouraBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pedraBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(papelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pedraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedraBtnActionPerformed
       jogada2 = 0;
        try {
            decideVencedor();
        } catch (SQLException ex) {
            Logger.getLogger(JogadaJog2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_pedraBtnActionPerformed

    private void papelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_papelBtnActionPerformed
          jogada2 = 1;
        try {
            decideVencedor();
        } catch (SQLException ex) {
            Logger.getLogger(JogadaJog2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_papelBtnActionPerformed

    private void tesouraBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tesouraBtnActionPerformed
         jogada2 = 2;
        try {
            decideVencedor();
        } catch (SQLException ex) {
            Logger.getLogger(JogadaJog2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tesouraBtnActionPerformed

   public void decideVencedor() throws SQLException{
    Jogada jogo = new Jogada();
    JogadaDAO jogaDAO = new JogadaDAO();

       if(JogadaJog1.jogada1 == 0 && jogada2 == 1){
           jogo.setVencedorJogada(2);
           jogaDAO.adicionaVencedorJogada(jogo);
       } else if(JogadaJog1.jogada1 == 0 && jogada2 == 2){
           jogo.setVencedorJogada(1);
           jogaDAO.adicionaVencedorJogada(jogo);
       }else if(JogadaJog1.jogada1 == 0 && jogada2 == 0){
            jogo.setVencedorJogada(0);
           jogaDAO.adicionaVencedorJogada(jogo);
       }else if(JogadaJog1.jogada1 == 1 && jogada2 == 0){
            jogo.setVencedorJogada(1);
           jogaDAO.adicionaVencedorJogada(jogo);
       }else if(JogadaJog1.jogada1 == 1 && jogada2 == 1){
           jogo.setVencedorJogada(0);
           jogaDAO.adicionaVencedorJogada(jogo);
       }else if(JogadaJog1.jogada1 == 1 && jogada2 == 2){
           jogo.setVencedorJogada(2);
           jogaDAO.adicionaVencedorJogada(jogo);
       }else if(JogadaJog1.jogada1 == 2 && jogada2 == 0){
           jogo.setVencedorJogada(2);
           jogaDAO.adicionaVencedorJogada(jogo);
       }else if(JogadaJog1.jogada1 == 2 && jogada2 == 1){
           jogo.setVencedorJogada(1);
           jogaDAO.adicionaVencedorJogada(jogo);
       }else if(JogadaJog1.jogada1 == 2 && jogada2 == 2){
           jogo.setVencedorJogada(0);
           jogaDAO.adicionaVencedorJogada(jogo);
       }
       
   }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogadaJog2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogadaJog2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogadaJog2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogadaJog2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogadaJog2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton papelBtn;
    private javax.swing.JButton pedraBtn;
    private javax.swing.JButton tesouraBtn;
    // End of variables declaration//GEN-END:variables
}
